spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:8787,http://taskboarding-frontend:8787,https://localhost:8787,https://taskboarding-frontend:8787"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Content-Type, Authorization, Origin"
            allow-credentials: true
            max-age: 3600
      routes:
        - id: route1
          uri: http://user-registration-microservice:8080/api/accounts/testcall
          predicates:
            - Path=/test
          filters:
            - SetPath=/api/accounts/testcall
        - id: route2
          uri: http://user-login-microservice:8282/api/accounts/login
          predicates:
            - Path=/login
          filters:
            - SetPath=/api/accounts/login
        - id: route3
          uri: http://user-registration-microservice:8080/api/accounts/create
          predicates:
            - Path=/register
          filters:
            - SetPath=/api/accounts/create

logging:
  level:
    root: DEBUG



