
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:8787,http://taskboarding-frontend:8787,https://localhost:8787,https://taskboarding-frontend:8787,http://localhost:8787,http://taskboarding-frontend:3001,https://localhost:3001,https://taskboarding-frontend:3001,http://localhost:3001, http://taskboarding-frontend.localhost:9080, http://taskboarding-frontend:9080, http://taskboarding-frontend-service:80/project/create, http://localhost:80/project/create"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Content-Type, Authorization, Origin, Accept, X-Requested-With, X-Auth-Token, method"
            allow-credentials: true
            max-age: 3600
      routes:
        - id: route1
          uri: http://user-registration-microservice:8080/api/accounts/testcall
          predicates:
            - Path=/test
          filters:
            - SetPath=/api/accounts/testcall
        - id: ${ROUTE_2_DEV_ID}
          uri: ${ROUTE_2_DEV_URI}
          predicates:
            - ${ROUTE_2_DEV_PREDICATES}
          filters:
            - ${ROUTE_2_DEV_FILTERS}
        - id: ${ROUTE_3_DEV_ID}
          uri: ${ROUTE_3_DEV_URI}
          predicates:
            - ${ROUTE_3_DEV_PREDICATES}
          filters:
            - ${ROUTE_3_DEV_FILTERS}
        - id: ${ROUTE_4_DEV_ID}
          uri: ${ROUTE_4_DEV_URI}
          predicates:
            - ${ROUTE_4_DEV_PREDICATES}
          filters:
            - ${ROUTE_4_DEV_FILTERS}
        - id: ${ROUTE_5_DEV_ID}
          uri: ${ROUTE_5_DEV_URI}
          predicates:
            - ${ROUTE_5_DEV_PREDICATES}
          filters:
            - ${ROUTE_5_DEV_FILTERS}
        - id: ${ROUTE_6_DEV_ID}
          uri: ${ROUTE_6_DEV_URI}
          predicates:
            - ${ROUTE_6_DEV_PREDICATES}
          filters:
           - ${ROUTE_6_DEV_FILTERS}
        - id: ${ROUTE_7_DEV_ID}
          uri: ${ROUTE_7_DEV_URI}
          predicates:
            - ${ROUTE_7_DEV_PREDICATES}
          filters:
            - ${ROUTE_7_DEV_FILTERS}

logging:
  level:
    root: DEBUG



